name: Update readme ⭐️ progress

on:
    push:
        branches: [ "main" ]
    schedule:
     - cron: "29 3 * * *"
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        if: ${{ vars.AOC_ENABLED == 'true' }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: k2bd/advent-readme-stars@v1
              with:
                  userId: ${{ vars.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ vars.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "update readme progress"
